### ISSUE TITLE
Add support for custom properties

### ISSUE THREAD

**Issue by pydsigner** [pydsigner/anchovy_css#1]
```css
p {
    my-property: 10px;
}
```
It would be easiest to support these in Python, but maybe more useful to allow them in Anchovy CSS as well:
```css
@anchovy-property (my-property, --size) {
    margin-left: calc(-2 * arg(--size));
    padding: arg(--size) 0;
}
```
